swagger: '2.0'
info:
  version: 0.0.1
  title: Shanoir NG Studies Microservice
  description: Microservice API for Shanoir NG study managment
produces:
  - application/json
paths:
  /studies:
    get:
      operationId: findStudies
      description: 'If exists, returns the studies that the user is allowed to see'
      responses:
        '200':
          description: found studies
          schema:
            type: array
            items:
              $ref: '#/definitions/Study'
        '204':
          description: no study found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      operationId: saveNewStudy
      description: Saves a new study
      consumes:
        - application/json
      parameters:
        - name: study
          in: body
          description: study to create
          required: true
          schema:
            $ref: '#/definitions/Study'
      responses:
        '200':
          description: created study
          schema:
            $ref: '#/definitions/Study'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/studies/{studyId}':
    get:
      operationId: findStudyById
      description: 'If exists, returns the study corresponding to the given id'
      parameters:
        - $ref: '#/parameters/studyId'
      responses:
        '200':
          description: found study
          schema:
            $ref: '#/definitions/Study'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    put:
      operationId: updateStudy
      description: Updates a study
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/studyId'
        - name: study
          in: body
          description: study to update
          required: true
          schema:
            $ref: '#/definitions/Study'
      responses:
        '204':
          description: study updated
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    delete:
      operationId: deleteStudy
      description: Deletes a study
      parameters:
        - $ref: '#/parameters/studyId'
      responses:
        '204':
          description: study deleted
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /studies/listwithcards:
    get:
      operationId: findStudiesWithStudyCardsByUserId
      description: >-
        If exists, returns the studies with theirs study cards that the user is
        allowed to see
      responses:
        '200':
          description: found studies
          schema:
            $ref: '#/definitions/SimpleStudyDTO'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /studies/names:
    get:
      operationId: findStudiesNames
      description: Returns id and name for all the studies
      responses:
        '200':
          description: found studies
          schema:
            type: array
            items:
              $ref: '#/definitions/IdNameDTO'
        '204':
          description: no study found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
parameters:
  studyId:
    name: studyId
    in: path
    description: id of the study
    required: true
    type: integer
    format: int64
definitions:
  IdNameDTO:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Study:
    type: object
    required:
      - id
      - name
      - status
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      status:
        $ref: '#/definitions/Status'
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
      clinical:
        type: boolean
      withExamination:
        type: boolean
      isVisibleByDefault:
        type: boolean
      isDownloadableByDefault:
        type: boolean
  SimpleStudyDTO:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      studyCards:
        type: array
        items:
          $ref: '#/definitions/SimpleStudyCardDTO'
  SimpleStudyCardDTO:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Status:
    type: object
    required:
      - id
      - labelName
    properties:
      id:
        type: integer
        format: int64
      labelName:
        type: string
  ErrorModel:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: object
      message:
        type: string
