# DataSource settings: set here your own configurations for the database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challengescoresmicroservice?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
  # Show or not log for each sql query
  jpa:
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jooq:
    sql-dialect: Mysql
