version: '3'
services:
  keycloak-database:
    container_name: shanoir-ng-keycloak-database
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    image: mysql/mysql-server
    networks:
      - shanoir_ng_network
    volumes:
      - "keycloak-database-data:/var/lib/mysql"
  keycloak:
    build: ./docker-compose/keycloak
    container_name: shanoir-ng-keycloak
    networks:
      - shanoir_ng_network
    ports:
     - "8080:8080"
networks:
  shanoir_ng_network:
volumes:
  keycloak-database-data: