# Shanoir NG - Import, manage and share neuroimaging data
# Copyright (C) 2009-2019 Inria - https://www.inria.fr/
# Contact us on https://project.inria.fr/shanoir/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html

version: '3'
services:

  datasets:
    volumes:
      - tmp3:/tmp
      - "datasets-data2:/var/datasets-data"
  
  studies:
    volumes:
      - "datasets-data2:/var/datasets-data"

  import:
    volumes:
      - tmp3:/tmp
  
  nginx:
    environment: 
      - SHANOIR_DEV=TRUE
    depends_on:
      - "front-dev"

  front-dev:
    container_name: front-dev
    build: ./docker-compose/front-dev
    volumes:
      - "./shanoir-ng-front:/app/"
    command: ng serve --host 0.0.0.0 --disableHostCheck
    ports:
     - "4200:4200"
    tty: true
    networks:
      - shanoir_ng_network

networks:
  shanoir_ng_network:
      
volumes:
  tmp3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tmp/
  
  datasets-data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/datasets-data/