# server configuration
server:
  port: 9900
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_centers?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/populate.sql
  jackson:
    mapper:
      use-getters-as-setters: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: rabbitmq
  session:
    store-type: none
#keycloak
keycloak:
  cors: true
  realm: shanoir-ng
  auth-server-url: http://shanoir-ng-nginx/auth
  ssl-required: external
  resource: shanoir-ng-centers
  securityConstraints[0]:
    securityCollections[0]:
      name: spring secured api
      authRoles: 
        - adminRole
        - expertRole
        - guestRole
        - userRole
      patterns:
        - /*
kc.requests:
    realm: master
    client.id: admin-cli
    admin:
      login: admin
      password: admin
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-centers.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_centers?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: root
    password: 
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/import.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: localhost
server:
    port: 9902
# logging configuration
logging:
  file: c:\\Temp\\shanoir-ng\\shanoir-ng-centers.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:SHANOIR_NG_CENTERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    data: classpath:/scripts/test-data-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
      
---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: qualif
  datasource:
    initialize: false
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
#keycloak
keycloak:
  auth-server-url: http://shanoir-ng-nginx/auth
      
