# server configuration
server:
  port: 9900
  error:
    whitelabel:
      enabled: false
# spring security configuration
security:
  sessions: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/populate.sql
  jackson:
    mapper:
      use-getters-as-setters: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: rabbitmq
  session:
    store-type: none
#keycloak
keycloak:
  cors: true
  realm: shanoir-ng
  realmKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1X1Yxc6iFhiqGHE/0+jbDGlZbSc/K2KRxXwShx6hdIRkgXw7caxKpl8+5D6i3GOtG9FZl8H0VZfbbReJQ9lXq/WygBKJHGrjkb4RoS1P3G47zDpg8sBIW+q4dyu7Nm98OXKhaRBPEfT7wt+0/zRrbbfh+IhJVzlFZ6KU/DS6tRsTBTi0xVL5U1hbpNA+oCy51P63blh0F0bAnMExNTjr9qhAdVv6mwwzh8MB52aln1rHhnfJtZEKLPV3IxlpwWKpDY58LwFGFTjoHLMaPkU7jf4/znD3I34evgA2VtXhTKakT8spX+0aBfTkSeR5Ix69b2LvgNCeY8kCKRANqWZbBQIDAQAB
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: shanoir-ng-users
  bearer-only: true
  credentials.secret: af0a63d8-8540-4bdc-b909-ee5866361dca
  securityConstraints[0]:
    securityCollections[0]:
      name: spring secured api
      authRoles: 
        - adminRole
        - ROLE_ADMIN
      patterns:
        - /*
kc.requests:
    realm: master
    client.id: security-admin-console
    admin:
      login: admin
      password: admin
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-users.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: root
    password: 
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/import.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: localhost
server:
    port: 9901
# logging configuration
logging:
  file: c:\\Temp\\shanoir-ng\\shanoir-ng-users.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:SHANOIR_NG_USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    data: classpath:/scripts/test-data-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
