######################################
# Default profile is production      #
######################################
server:
  port: 9901
  error:
    whitelabel:
      enabled: false
  display-name: Shanoir
  administrator.email: shanoir-dev-test@lists.gforge.inria.fr
##### Database #####
spring:
  datasource:
    url: jdbc:mysql://database:3306/users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: users
    password: password
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    data: classpath:/scripts/import.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
##### Others #####
  jackson:
    mapper:
      use-getters-as-setters: false
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: rabbitmq
    port: 5672
  session:
    store-type: none
  mail:
    host: SMTP_HOST
    port: 25
    properties:
      mail.smtp.from: do-not-reply@inria.fr
front.server:
  address: http://shanoir-ng-nginx/shanoir-ng/
  url: http://shanoir-ng-nginx
##### Keycloak #####
keycloak:
  # attention: this config for the token issuer needs to match the domain of the frontend
  # used for token creation AND the server url needs to be known from inside the docker network:
  auth-server-url: http://shanoir-ng-nginx/auth
  cors: true
  realm: shanoir-ng
  resource: shanoir-ng-users
  ssl-required: external
  securityConstraints:
    - authRoles: 
      - ROLE_ADMIN
      - ROLE_EXPERT
      - ROLE_GUEST
      - ROLE_USER
    - securityCollections:
      - name: user secured api
      - patterns:
        - /user/*
    - securityCollections:
      - name: role secured api
      - patterns:
        - /role/*
kc:
# used to verify, that the login date update comes really from Keycloak in the network:
  host.name: keycloak
  requests:
    realm: master
    client.id: admin-cli
# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-users.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    initialize: true
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true

# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-users.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR