# server configuration
server:
  administrator.email: shanoir-dev-test@lists.gforge.inria.fr
  display-name: Shanoir
  error:
    whitelabel:
      enabled: false
  port: 9900
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
  jackson:
    mapper:
      use-getters-as-setters: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  jooq:
    sql-dialect: Mysql
  mail:
    host: smtp.inria.fr
    port: 25
    properties:
      mail.smtp.from: do-not-reply@inria.fr
  rabbitmq:
    host: shanoir-ng-rabbitmq
  session:
    store-type: none
front.server:
  address: http://localhost/shanoir-ng/
  url: http://shanoir-ng-nginx
#keycloak
keycloak:
  auth-server-url: http://shanoir-ng-nginx/auth
  cors: true
  realm: shanoir-ng

  realmKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl3ydNkdhOQkZ6DV9vF5EdGaNb2nbuMzy2zJiVdSvBTKDegj1HyzqFuy2lRbbpSNO2R9fJpkmvknlC8XyRObg+OdYrXWeevqfXMv21sFN3Yx5cen28xpCCLXAvxS9SdR3BkqyLkaxkpY5HKvklajJEMuN1xiIJdlfrMGGdClzguCX2L5ITgBDU8BZh1UGgCeoFpQPhiJfuxJ9THp58DxPVNUVJwSEancAajWKZF+pnEYnpw81QfzdvhZkwxftnPqNWErOEf9JY2ptGZFIY2PesmZ8RI3u4Kq0gwVl7Kn64qBoN07SPHCWZ8n758hRe/1SLqBMvcfoDRs9IlGZDGOteQIDAQAB
  auth-server-url: http://localhost/auth
  ssl-required: external

  resource: shanoir-ng-users
  ssl-required: external
  securityConstraints:
    - authRoles: 
      - ROLE_ADMIN
      - ROLE_EXPERT
      - ROLE_GUEST
      - ROLE_USER
    - securityCollections:
      - name: user secured api
      - patterns:
        - /user/*
    - securityCollections:
      - name: role secured api
      - patterns:
        - /role/*
kc:
  host.name: shanoir-ng-keycloak
  requests:
    realm: master
    client.id: admin-cli
    admin:
      login: admin
      password: admin
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-users.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: root
    password: WelcomeShanoir1
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: update
    # Show or not log for each sql query
    show-sql: true
  jooq:
    sql-dialect: Mysql
  mail:
    host: localhost
  rabbitmq:
    host: localhost
server:
  port: 9901
front.server:
  address: http://localhost:8080/shanoir-ng/
  url: http://localhost:8080
#keycloak
keycloak:

  credentials.secret: 27cee53d-3c37-42d6-947d-0889667e6608
  auth-server-url: http://localhost:8080/auth
  #credentials.secret: 3b130530-4e0f-4101-bf56-1a92df705318
#kc.requests:
  #auth-server-url: http://localhost/auth

# logging configuration
logging:
  file: c:\\Temp\\shanoir-ng\\shanoir-ng-users.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:SHANOIR_NG_USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    data: classpath:/scripts/test-data-h2.sql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
  mail:
    host: localhost
    port: 3025

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: qualif
  datasource:
    initialize: false
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
  rabbitmq:
    host: shanoir-ng-rabbitmq
  mail:
    host: SMTP_HOST
    port: 25
    properties:
      mail.smtp.from: do-not-reply@inria.fr
server:
  administrator.email: SHANOIR_ADMIN_EMAIL
front.server:
  address: SHANOIR_SERVER_URL/
  url: SHANOIR_SERVER_URL
#keycloak
keycloak:
  auth-server-url: SHANOIR_SERVER_URL/auth
kc:
  host.name: shanoir-ng-keycloak
  requests:
    realm: master
    client.id: admin-cli
    admin:
      login:    KEYCLOAK_USER
      password: KEYCLOAK_PASSWORD
