# server configuration
server:
  port: 9900
  error:
    whitelabel:
      enabled: false
# zuul configuration
# as url is used: no service discovery with service-id
#zuul:
#  routes:
#    resource:
#      path: /resource/**
#      url: http://resource:9901
#      sensitive-headers: 
# spring security configuration
security:
  sessions: never
  user:
    password: password
# redis configuration
spring:
  redis:
    host: localhost
# logging configuration
logging:
  file: shanoir-ng-main.log