# server configuration
server:
  port: 9900
  error:
    whitelabel:
      enabled: false
# zuul configuration
# as url is used: no service discovery with service-id
#zuul:
#  routes:
#    resource:
#      path: /resource/**
#      url: http://resource:9901
#      sensitive-headers:
# spring security configuration
security:
  sessions: never
  user:
    password: password
spring:
  # redis configuration
  redis:
    host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
  # Show or not log for each sql query
  jpa:
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect
  jooq:
    sql-dialect: Mysql
# logging configuration
logging:
  file: shanoir-ng-user.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR