# server configuration
server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
  session:
    store-type: none
#keycloak
keycloak:
  realm: shanoir-ng
  auth-server-url: http://shanoir-ng-nginx/auth
kc.requests:
  admin:
    login: admin
    password: admin
  client.id: admin-cli
  realm: master
  temporary.password: false
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-keycloak-init.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: root
    password: 
#keycloak
keycloak:
  realm: shanoir-ng
  auth-server-url: http://localhost:8080/auth
kc.requests:
  admin:
    login: admin
    password: admin
  client.id: admin-cli
  realm: master
  temporary.password: false
# logging configuration
logging:
  file: c:\\Temp\\shanoir-ng\\shanoir-ng-init-keycloak.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: qualif
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    initialize: false
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
#keycloak
keycloak:
  realm: shanoir-ng
  auth-server-url: http://shanoir-ng-nginx/auth
kc.requests:
  admin:
    login: admin
    password: admin
  client.id: admin-cli
  realm: master
  temporary.password: true
