# server configuration
server:
  port: 9900
  error:
    whitelabel:
      enabled: false
# spring security configuration
security:
  sessions: never
spring:
  # redis configuration
  redis:
    host: shanoir-ng-redis
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_template?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/populate.sql
  jackson:
    mapper:
      use-getters-as-setters: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: rabbitmq
#keycloak
keycloak:
  cors: true
  realm: demo
  realmKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmgMaWeSsqzD6zkYxRl+X2kXnv6jvT9/juPzxBD8T5Fp2+4erfxnZ69UGqVtGNaKR0CF0wvr3a9S3jf4hhBkWBeLcZp+VEyZHRy1v+lNoFCtc0owIqvlEy85I0X5bScSn9kcex8aIELnuPtSB+D+78JYgdhLsriIJQcYYqr8YMUJThakKCzHidf8p33aiI+pJE889/hh2xB47u/KIe+9lTKnwqs11ooX5QiOTOwJtX+/AFn7m8xnhiQygDT+e3dT2RR1CjkS6b+bdu9xS7BsUpypJlSGckjhUoGC3lXePGIRMbl3DM+Z5Yc0fWlP2aZvTYhT+G1jzwpf+wIAChUnPjwIDAQAB
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: springboot
  bearer-only: true
  credentials.secret: 6a85f996-a162-4366-b1a8-6e1ff4b36210
  securityConstraints[0]:
    securityCollections[0]:
      name: spring secured api
      authRoles: 
        - adminRole
        - ROLE_ADMIN
      patterns:
        - /*
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-users.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_template?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: root
    password: 
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/import.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: localhost
  # redis configuration
  redis:
    host: localhost
server:
    port: 9902
# logging configuration
logging:
  file: c:\\Temp\\shanoir-ng\\shanoir-ng-users.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:SHANOIR_NG_USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    data: classpath:/scripts/test-data-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
