swagger: '2.0'
info:
  version: 0.0.1
  title: Shanoir NG Studies Microservice
  description: Microservice API for Shanoir NG study managment
produces:
  - application/json
paths:
  /study:
    post:
      operationId: saveNewStudy
      description: Saves a new study
      consumes:
        - application/json
      parameters:
        - name: study
          in: body
          description: study to create
          required: true
          schema:
            $ref: '#/definitions/Study'
      responses:
        '200':
          description: created study
          schema:
            $ref: '#/definitions/Study'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/study/{studyId}':
    get:
      operationId: findStudyById
      description: 'If exists, returns the study corresponding to the given id'
      parameters:
        - $ref: '#/parameters/studyId'
      responses:
        '200':
          description: found study
          schema:
            $ref: '#/definitions/Study'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    put:
      operationId: updateStudy
      description: Updates a study
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/studyId'
        - name: study
          in: body
          description: study to update
          required: true
          schema:
            $ref: '#/definitions/Study'
      responses:
        '204':
          description: study updated
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '422':
          description: bad parameters
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    delete:
      operationId: deleteStudy
      description: Deletes a study
      parameters:
        - $ref: '#/parameters/studyId'
      responses:
        '204':
          description: study deleted
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /study/all:
    get:
      operationId: findStudies
      description: Returns all the studies
      responses:
        '200':
          description: found studies
          schema:
            type: array
            items:
              $ref: '#/definitions/Study'
        '204':
          description: no study found
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  '/study/{userId}/allStudies':
    get:
      operationId: findStudiesByUserId
      description: 'If exists, returns the studies that the user is allowed to see'
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: found studies
          schema:
            $ref: '#/definitions/Study'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: no study found
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
parameters:
  studyId:
    name: studyId
    in: path
    description: id of the study
    required: true
    type: integer
    format: int64
  userId:
    name: userId
    in: path
    description: id of the user
    required: true
    type: integer
    format: int64
definitions:
  Study:
    type: object
    required:
      - id
      - name
      - status
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      status:
        type: string
        enum:
          - FINISHED
          - IN PROGRESS
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
      clinical:
        type: boolean
      withExamination:
        type: boolean
      isVisibleByDefault:
        type: boolean
      isDownloadableByDefault:
        type: boolean
  ErrorModel:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: object
      message:
        type: string
