# server configuration
server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
  session:
    store-type: none
  mail:
    host: SMTP_HOST
    port: 25
    properties:
      mail.smtp.from: do-not-reply@inria.fr
  rabbitmq:
    host: shanoir-ng-rabbitmq
#keycloak
keycloak:
  realm: shanoir-ng
  auth-server-url: http://shanoir-ng-keycloak:8080/auth
kc.requests:
  client.id: admin-cli
  realm: master
  # DANGEROUS, DO NOT ENABLE IN PRODUCTION. Used to set same password to all users on database initialization.
  debug.use.dummy.password: false
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-keycloak-init.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
  jooq:
    sql-dialect: Mysql
#keycloak
keycloak:
  auth-server-url: http://localhost/auth
kc.requests.debug.use.dummy.password: true
# logging configuration
logging:
  file: c:\\Temp\\shanoir-ng\\shanoir-ng-keycloak-init.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: qualif,prod
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    initialize: false
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
  mail:
    host: SMTP_HOST
    port: SMTP_PORT
    properties:
      mail.smtp.from: do-not-reply@inria.fr
#keycloak
keycloak:
  auth-server-url: SHANOIR_SERVER_URL/auth
