# Create a Docker image for each microservice in Shanoir
name: Publish Docker images

#on:
#  release:
#    types: [published]
#on:
#  push:
#    branches: [ master ]
# use manual runs for testing purpose
on: workflow_dispatch

jobs:
  push_to_registries:
    name: Push Docker image to Container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Create directory /shanoir-ng-logs
        run: sudo mkdir -m777 /var/log/shanoir-ng-logs
      - name: Build with Maven
        run: mvn -f ./shanoir-ng-parent/pom.xml install -DskipTests
        env:
          SHANOIR_URL_HOST: localhost
          SHANOIR_URL_SCHEME: http
          SHANOIR_PREFIX: github
          SHANOIR_ADMIN_EMAIL: nobody@inria.fr
          SHANOIR_KEYCLOAK_USER: admin
          SHANOIR_KEYCLOAK_PASSWORD: '&a1A&a1A'
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: |
            shanoir-ng/shanoir-ng
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          context: ./docker-compose/users
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
